apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-actions-runner.fullname" . }}-mirrors
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
    app.kubernetes.io/component: mirrors
data:
  credentials.json: {{ include "github-actions-runner.credentialsFile" . | fromYaml | toJson | b64enc | quote }}
