# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: mongosync
description: Mongo Cluster-to-Cluster Sync
type: application
home: https://github.com/sergelogvinov/helm-charts
icon: https://raw.githubusercontent.com/sergelogvinov/helm-charts/main/charts/mongosync/icon.png
sources:
- https://github.com/sergelogvinov/helm-charts/tree/master/charts/mongosync
- https://www.mongodb.com/docs/cluster-to-cluster-sync
keywords:
- mongodb
- mongosync
maintainers:
- name: sergelogvinov
  url: https://github.com/sergelogvinov

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.5

appVersion: "1.8.0"
