{{ if .Values.developers  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rbac-common.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "rbac-common.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.rbac.singleNamespace }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ include "rbac-common.fullname" . }}:edit
subjects:
{{- range .Values.developers }}
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ . }}
{{- end }}
{{- end }}
