# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: teamcity
description: Teamcity on Kubernetes
type: application
home: https://github.com/sergelogvinov/helm-charts
icon: https://raw.githubusercontent.com/sergelogvinov/helm-charts/main/charts/teamcity/icon.png
sources:
  - https://github.com/sergelogvinov/helm-charts/tree/master/charts/teamcity
  - https://www.jetbrains.com/teamcity
keywords:
  - ci
  - continuous integration
  - continuous delivery
  - continuous deployment
  - devops
  - automation
maintainers:
  - name: sergelogvinov
    url: https://github.com/sergelogvinov
# dependencies: []
#   - name: postgresql-single
#     version: ~0.10.6
#     repository: https://helm-charts.sinextra.dev
#     condition: postgresql.enabled
#
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.7.3
#
# renovate: datasource=docker depName=ghcr.io/sergelogvinov/teamcity
appVersion: 2024.07.3
