apiVersion: v2
name: system-upgrade-controller
description: System Upgrade Controller for Talos
type: application
home: https://github.com/sergelogvinov/helm-charts
sources:
  - https://github.com/sergelogvinov/helm-charts/tree/main/charts/system-upgrade-contoller
keywords:
  - system-upgrade-controller
  - talos
maintainers:
  - name: sergelogvinov
    url: https://github.com/sergelogvinov
#
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.3
#
# renovate: datasource=docker depName=rancher/system-upgrade-controller
appVersion: "v0.15.2"
