# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: ipsec
description: IPSec link for Kubernetes
type: application
home: https://github.com/sergelogvinov/helm-charts
icon: https://raw.githubusercontent.com/sergelogvinov/helm-charts/main/charts/ipsec/icon.png
sources:
  - https://github.com/sergelogvinov/helm-charts/tree/main/charts/ipsec
  - https://libreswan.org/
keywords:
  - ipsec
  - vpn
maintainers:
  - name: sergelogvinov
    url: https://github.com/sergelogvinov
#
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.6.0
#
# renovate: datasource=docker depName=ghcr.io/sergelogvinov/ipsec
appVersion: "5.2"
