# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: keydb
description: KeyDB with TLS, backup/restore support
type: application
home: https://github.com/sergelogvinov/helm-charts
icon: https://raw.githubusercontent.com/sergelogvinov/helm-charts/main/charts/keydb/icon.svg
sources:
  - https://github.com/sergelogvinov/helm-charts/tree/master/charts/keydb
  - https://docs.keydb.dev
  - https://github.com/wal-g/wal-g
keywords:
  - keydb
  - redis
  - wal-g
maintainers:
  - name: sergelogvinov
    url: https://github.com/sergelogvinov
#
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.16.0
#
# renovate: datasource=docker depName=ghcr.io/sergelogvinov/keydb
appVersion: "6.3.3"
