# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: fluentd
description: Deploy fluentd as log router
type: application
home: https://github.com/sergelogvinov/helm-charts
icon: https://raw.githubusercontent.com/fluent/fluentd-docs/master/public/logo/Fluentd_square.png
sources:
- https://github.com/sergelogvinov/helm-charts/tree/master/charts/fluentd
- https://www.fluentd.org
keywords:
- fluentd
- logging
- logs
maintainers:
- name: sergelogvinov
  url: https://github.com/sergelogvinov

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.4
appVersion: "1.16.2"
