# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: fluentd
description: Deploy fluentd as log router
type: application
home: https://github.com/sergelogvinov/helm-charts
icon: https://raw.githubusercontent.com/fluent/fluentd-docs/master/public/logo/Fluentd_square.png
sources:
  - https://github.com/sergelogvinov/helm-charts/tree/master/charts/fluentd
  - https://www.fluentd.org
keywords:
  - fluentd
  - logging
  - logs
maintainers:
  - name: sergelogvinov
    url: https://github.com/sergelogvinov
#
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.4.0
#
# renovate: datasource=docker depName=ghcr.io/sergelogvinov/fluentd
appVersion: 1.19.0
