apiVersion: v2
name: link-common
description: Simple vpn-p2p-link service
type: application
home: https://github.com/sergelogvinov/helm-charts
sources:
- https://github.com/sergelogvinov/helm-charts/tree/master/charts/link-common
keywords:
maintainers:
- name: sergelogvinov
  url: https://github.com/sergelogvinov

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.8.3-alpine3.18"
