# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: link-common
description: Simple vpn-p2p-link service
type: application
home: https://github.com/sergelogvinov/helm-charts
icon: https://raw.githubusercontent.com/sergelogvinov/helm-charts/main/charts/link-common/icon.png
sources:
  - https://github.com/sergelogvinov/helm-charts/tree/main/charts/link-common
keywords:
  - networking
  - vpn
maintainers:
  - name: sergelogvinov
    url: https://github.com/sergelogvinov
#
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.4.1
#
# renovate: datasource=docker depName=ghcr.io/sergelogvinov/haproxy
appVersion: "2.8.6-alpine3.19"
