# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: backend-common
description: Deploy common backend services with workers and jobs
type: application
home: https://github.com/sergelogvinov/helm-charts
icon: https://raw.githubusercontent.com/sergelogvinov/helm-charts/main/charts/backend-common/icon.png
sources:
- https://github.com/sergelogvinov/helm-charts/tree/main/charts/backend-common
keywords:
- backend
maintainers:
- name: sergelogvinov
  url: https://github.com/sergelogvinov

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.3

appVersion: "1.0.0"
