# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: prometheus-rules
description: Static prometheus/victoria metrics common rules
type: application
home: https://github.com/sergelogvinov/helm-charts
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
sources:
  - https://github.com/sergelogvinov/helm-charts/tree/main/charts/prometheus-rules
keywords:
  - prometheus
  - victoria-metrics
  - metrics
maintainers:
  - name: sergelogvinov
    url: https://github.com/sergelogvinov
#
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.19
#
appVersion: "2.40.0"
