apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
type: Opaque
data:
  backupPassword: {{ include "clickhouse.backupPassword" . | b64enc | quote }}
{{- range $key, $val := .Values.cronjobs }}
{{- if $val.envs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" $ }}-{{ $key }}-envs
  labels:
    {{- include "clickhouse.labels" $ | nindent 4 }}
type: Opaque
data:
{{- range $key,$value := $val.envs }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
