# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: pgbouncer
description: Postgres connection poller
type: application
home: https://github.com/sergelogvinov/helm-charts
icon: https://raw.githubusercontent.com/sergelogvinov/helm-charts/main/charts/pgbouncer/icon.png
sources:
  - https://github.com/sergelogvinov/helm-charts/tree/main/charts/pgbouncer
keywords:
  - pgbouncer
  - postgresql
maintainers:
  - name: sergelogvinov
    url: https://github.com/sergelogvinov
#
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.11.0
#
# renovate: datasource=docker depName=ghcr.io/sergelogvinov/pgbouncer
appVersion: "16.10"
