# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: mongosqld
description: Mongo to SQL bridge
type: application
home: https://github.com/sergelogvinov/helm-charts
icon: https://raw.githubusercontent.com/sergelogvinov/helm-charts/main/charts/mongosqld/icon.png
sources:
  - https://github.com/sergelogvinov/helm-charts/tree/master/charts/mongosqld
  - https://www.mongodb.com/docs/bi-connector/current/reference/mongosqld
keywords:
  - mongodb
  - mongosqld
  - powerbi
maintainers:
  - name: sergelogvinov
    url: https://github.com/sergelogvinov
#
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.7
#
# renovate: datasource=docker depName=ghcr.io/sergelogvinov/mongosqld
appVersion: "2.14.23"
