# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: registry-mirrors
description: Container registry mirror
type: application
home: https://github.com/sergelogvinov/helm-charts
icon: https://raw.githubusercontent.com/sergelogvinov/helm-charts/main/charts/registry-mirrors/icon.png
sources:
- https://github.com/sergelogvinov/helm-charts/tree/master/charts/registry-mirrors
keywords:
- containerd
- docker mirror
maintainers:
- name: sergelogvinov
  url: https://github.com/sergelogvinov

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.0

appVersion: "2.8.1"
