apiVersion: v2
name: bitwarden
description: A Helm chart to deploy Bitwarden.
type: application
home: https://github.com/sergelogvinov/helm-charts
icon: https://raw.githubusercontent.com/bitwarden/brand/master/icons/icon-square.svg
sources:
- https://github.com/sergelogvinov/helm-charts/tree/master/charts/bitwarden
- https://github.com/dani-garcia/vaultwarden
keywords:
- vaultwarden
- bitwarden
maintainers:
- name: sergelogvinov
  url: https://github.com/sergelogvinov

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.5

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.32.0"
