# Default values for rbac-common.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rbac:
  create: true
  singleNamespace: false

viewers: []
  # - user1
  # - user2

developers: []
  # - user1
  # - user2

clusterAdmins: []
  # - root1
