# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: service-common
description: Simple gateway with TLS auth
type: application
home: https://github.com/sergelogvinov/helm-charts
sources:
  - https://github.com/sergelogvinov/helm-charts/tree/master/charts/service-common
keywords:
  - haproxy
  - gateway
maintainers:
  - name: sergelogvinov
    url: https://github.com/sergelogvinov
#
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.5
#
# renovate: datasource=docker depName=haproxy
appVersion: 2.8.17
