# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: github-actions-runner
description: Github Actions with container registry and mirrors
type: application
home: https://github.com/sergelogvinov/helm-charts
icon: https://avatars.githubusercontent.com/u/44036562
sources:
- https://github.com/sergelogvinov/helm-charts/tree/master/charts/github-actions-runner
- https://github.com/actions/actions-runner-controller.git
keywords:
- github-actions
- conteiner
- docker-registry
- docker-mirror
maintainers:
- name: sergelogvinov
  url: https://github.com/sergelogvinov
#
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.0.2
#
# renovate: datasource=docker depName=ghcr.io/sergelogvinov/github-actions-runner
appVersion: 2.320.0
