apiVersion: v2
name: github-actions-runner
description: Github Actions with container registry and mirrors
type: application
home: https://github.com/sergelogvinov/helm-charts
sources:
- https://github.com/sergelogvinov/helm-charts/tree/master/charts/github-actions-runner
- https://github.com/actions/actions-runner-controller.git
keywords:
- github-actions
- conteiner
- docker-registry
- docker-mirror
maintainers:
- name: sergelogvinov
  url: https://github.com/sergelogvinov

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.6.2
appVersion: 2.317.0
