apiVersion: v2
name: overprovisioner
description: Reserve the resources for the migration
type: application
home: https://github.com/sergelogvinov/helm-charts
icon: https://raw.githubusercontent.com/sergelogvinov/helm-charts/main/charts/overprovisioner/icon.png
sources:
- https://github.com/sergelogvinov/helm-charts/tree/master/charts/overprovisioner
keywords:
- kubernetes
maintainers:
- name: sergelogvinov
  url: https://github.com/sergelogvinov

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.2
appVersion: "3.6"
