# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: overprovisioner
description: Reserve the resources for the migration
type: application
home: https://github.com/sergelogvinov/helm-charts
icon: https://raw.githubusercontent.com/sergelogvinov/helm-charts/main/charts/overprovisioner/icon.png
sources:
  - https://github.com/sergelogvinov/helm-charts/tree/master/charts/overprovisioner
keywords:
  - kubernetes
  - overprovisioner
maintainers:
  - name: sergelogvinov
    url: https://github.com/sergelogvinov
#
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.1
#
# renovate: datasource=docker depName=registry.k8s.io/pause
appVersion: "3.10.1"
