# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: clickhouse
description: Clickhouse chart for Kubernetes
type: application
home: https://github.com/sergelogvinov/helm-charts
icon: https://github.com/ClickHouse/clickhouse-docs/raw/84f38d893eb7e561c7296279d7953b6a508ec413/static/img/clickhouse-logo.svg
sources:
  - https://github.com/sergelogvinov/helm-charts/tree/master/charts/clickhouse
  - https://github.com/ClickHouse/ClickHouse
  - https://hub.docker.com/r/clickhouse/clickhouse-server
keywords:
  - database
maintainers:
  - name: sergelogvinov
    url: https://github.com/sergelogvinov
#
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.7.10
#
# renovate: datasource=docker depName=clickhouse/clickhouse-server
appVersion: 24.10.4
