# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: postgresql-single
description: Postgres with backup/restore and replication
type: application
home: https://github.com/sergelogvinov/helm-charts
icon: https://raw.githubusercontent.com/sergelogvinov/helm-charts/main/charts/postgresql-single/icon.png
sources:
  - https://github.com/sergelogvinov/helm-charts/tree/main/charts/postgresql-single
keywords:
  - postgresql
  - postgres
  - cloudnative-pg
  - database
  - sql
  - replication
maintainers:
  - name: sergelogvinov
    url: https://github.com/sergelogvinov
#
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.10.5
#
# renovate: datasource=docker depName=ghcr.io/sergelogvinov/postgresql
appVersion: "16.11"
