# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: tabix
description: Clickhouse WebUI
type: application
home: https://github.com/sergelogvinov/helm-charts
sources:
  - https://github.com/sergelogvinov/helm-charts/tree/master/charts/tabix
  - https://github.com/tabixio/tabix
keywords:
  - tabix
  - clickhouse
maintainers:
  - name: sergelogvinov
    url: https://github.com/sergelogvinov
#
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.0
#
# renovate: datasource=docker depName=ghcr.io/sergelogvinov/tabix
appVersion: "22.05.17"
