# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: mongodb-backup
description: Mongo backup with restore checks
type: application
home: https://github.com/sergelogvinov/helm-charts
icon: https://raw.githubusercontent.com/sergelogvinov/helm-charts/main/charts/mongodb-backup/icon.png
sources:
  - https://github.com/sergelogvinov/helm-charts/tree/master/charts/mongodb-backup
  - https://www.mongodb.com
  - https://github.com/wal-g/wal-g
keywords:
  - mongodb
  - backup
  - wal-g
maintainers:
  - name: sergelogvinov
    url: https://github.com/sergelogvinov
#
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.2
#
# renovate: datasource=docker depName=ghcr.io/sergelogvinov/mongodb
appVersion: 8.0.6
