# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: skipper
description: Ingress controller for Kubernetes
type: application
home: https://github.com/sergelogvinov/helm-charts
icon: https://raw.githubusercontent.com/sergelogvinov/helm-charts/main/charts/skipper/icon.png
sources:
  - https://github.com/sergelogvinov/helm-charts/tree/main/charts/skipper
keywords:
  - ingress-controller
  - skipper
maintainers:
  - name: sergelogvinov
    url: https://github.com/sergelogvinov
#
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.4.1
#
# renovate: datasource=docker depName=ghcr.io/zalando/skipper
appVersion: v0.24.12
